# ansible/roles/grafana/tasks/main.yml
---
- name: Add Grafana GPG key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
    
- name: Add Grafana repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    
- name: Install Grafana
  apt:
    name: grafana
    state: present
    update_cache: yes
    
- name: Configure Grafana
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: root
    group: grafana
    mode: '0644'
  notify: restart grafana

- name: Enable and start Grafana
  systemd:
    name: grafana-server
    enabled: yes
    state: started

    